---
#  ____  _                                    _    
# |  _ \| |_   _  __ _ _____      _____  _ __| | __
# | |_) | | | | |/ _` / __\ \ /\ / / _ \| '__| |/ /
# |  __/| | |_| | (_| \__ \\ V  V / (_) | |  |   < 
# |_|   |_|\__,_|\__, |___/ \_/\_/ \___/|_|  |_|\_\
#                |___/
# @copyright (c) 2016 All rights reserved, Plugswork
# @author    Plugswork Codx
# @website   https://plugswork.com/

#Server ID is a ID used by Plugswork to create connection with our server
#You need to register your server at (https://plugswork.com/panel/server-add)
#to get a unique Server ID for your server
server-id: steve-0000
#Secret Key can be found at your Profile Page
#Link: https://plugswork.com/panel/account/
secret-key:

#Set the type of the database provider used
#Default: sqlite [sqlite/mysql]
provider: sqlite
#Config for MySQL Database if provider is set to mysql
options: 
  host: localhost
  port: 3306
  user: user
  password: password
  database: plugswork_data
...